# Generated by Django 3.2.12 on 2022-02-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_auto_20220227_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sequence',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('to_do', 'To do'), ('in_progress', 'In progress'), ('done', 'Done')], default='to_do', max_length=255),
        ),
    ]
