# Generated by Django 3.2.12 on 2022-02-27 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_auto_20220227_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user_id',
            new_name='user',
        ),
    ]
