# Generated by Django 3.2.12 on 2022-02-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0006_rename_user_id_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sequence',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
