# Generated by Django 3.2.12 on 2022-02-27 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0008_rename_last_modified_when_task_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='slug',
        ),
    ]
