# Generated by Django 3.2.12 on 2022-02-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0010_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='last_updated',
            field=models.DateTimeField(),
        ),
    ]
